### ISSUE TITLE
Percentile Aggregation not working

### ISSUE THREAD

**Issue by sakthiraam** [piotr1212/grafana-dynatrace-datasource#3]
Hi Piotr, Thanks for the plug-in. It's working properly for all other aggregations but for percentiles Dynatrace API is looking for the percentile value to be provided in the request (say 50th percentile, 90th percentile etc). So the current plug-in fails with HTTP 400 as the request doesn't have sufficient information for the API to process. Can you please help to change the plugin to allow us to input this information.

Thank You
Sakthi

**Comment by piotr1212** [comment]
Happy to hear it is useful.

I've created this plugin for one of my customers. I'm not working for them any more and don't even have access to a Dynatrace server. Unfortunately I don't have time to work on this at the moment...

That said, the source is open, it shouldn't be to hard for an experienced JavaScript developer to implement this.

**Comment by piotr1212** [comment]
This is implemented in https://github.com/piotr1212/grafana-dynatrace-datasource/pull/5
